openapi: 3.0.0
paths:
  /user:
    get:
      operationId: createUser
      responses:
        default:
          description: 'successful operation'
          content:
            application/json:
              schema:
                description: Somethings
                type: string
